# Generated by Django 3.2.6 on 2021-11-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replyronment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='slug',
            field=models.SlugField(default='', max_length=200, null=True, unique=True),
        ),
    ]
