# Generated by Django 3.2.6 on 2021-11-11 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('replyronment', '0003_commentforum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentforum',
            name='forum_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to='replyronment.forumpost'),
        ),
        migrations.AlterField(
            model_name='commentforum',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
